"""Training entry points for SuperBot reinforcement learning."""
from __future__ import annotations

import argparse
import json
from dataclasses import dataclass
from pathlib import Path
from typing import List, Optional

import numpy as np

from rl_components import ImitationDataset, ImitationExample, PolicyFactory, PolicyManager, ReplayBuffer, Transition, default_dqn_factory, train_imitation


@dataclass
class TrainingConfig:
    episodes: int = 500
    steps_per_episode: int = 1200
    epsilon_start: float = 1.0
    epsilon_final: float = 0.05
    epsilon_decay: float = 0.995
    gamma: float = 0.99
    batch_size: int = 128
    warmup: int = 1000
    checkpoint_dir: Path = Path("models")
    imitation_replays: Optional[Path] = None
    use_subprocess_env: bool = False


def linear_schedule(start: float, end: float, step: float) -> float:
    return max(end, start * step)


def load_imitation_examples(replay_dir: Path) -> List[ImitationExample]:
    """Load imitation data from JSON traces generated by ``record_training``."""

    examples: List[ImitationExample] = []
    for path in replay_dir.glob("*.json"):
        data = json.loads(path.read_text())
        for frame in data:
            state = np.asarray(frame["state"], dtype=np.float32)
            action = int(frame["action"])
            examples.append(ImitationExample(state=state, action=action))
    return examples


def train(config: TrainingConfig, policy_factory: PolicyFactory = default_dqn_factory()) -> None:
    from rlgym.envs import Match
    from rlgym.gym import Gym
    from rlgym.utils.obs_builders.default import DefaultObs
    from rlgym.utils.action_parsers.default_act import DefaultAction
    from rlgym.utils.reward_functions.common_rewards import LiuDistancePlayerToBallReward

    match = Match(
        team_size=1,
        obs_builder=DefaultObs(),
        action_parser=DefaultAction(),
        reward_function=LiuDistancePlayerToBallReward(),
    )
    env = Gym(match=match, self_play=True, team_size=1)

    sample_state = env.reset()
    state_dim = int(np.asarray(sample_state).size)
    action_dim = int(env.action_space.n)

    policy: PolicyManager = policy_factory.build(state_dim, action_dim)
    buffer = ReplayBuffer(capacity=200_000)

    epsilon = config.epsilon_start
    if config.imitation_replays and config.imitation_replays.exists():
        examples = load_imitation_examples(config.imitation_replays)
        if examples:
            dataset = ImitationDataset(examples)
            print(f"Pretraining with {len(dataset)} imitation samples")
            train_imitation(policy, dataset, epochs=10)

    for episode in range(config.episodes):
        state = np.asarray(env.reset(), dtype=np.float32)
        episode_reward = 0.0
        for step in range(config.steps_per_episode):
            action = policy.select_action(state, epsilon)
            next_state, reward, done, _ = env.step(action)
            next_state = np.asarray(next_state, dtype=np.float32)
            buffer.push(Transition(state=state, action=action, reward=float(reward), next_state=next_state, done=done))
            state = next_state
            episode_reward += reward
            if len(buffer) > config.warmup:
                loss = policy.optimize(buffer, batch_size=config.batch_size, gamma=config.gamma)
            if done:
                break

        epsilon = linear_schedule(epsilon, config.epsilon_final, config.epsilon_decay)
        print(f"Episode {episode+1}/{config.episodes} reward={episode_reward:.2f} epsilon={epsilon:.3f}")

        if (episode + 1) % 25 == 0:
            checkpoint_path = config.checkpoint_dir / f"dqn_{episode+1:04d}.pt"
            policy.save(checkpoint_path)
            print(f"Saved checkpoint to {checkpoint_path}")

    policy.save(config.checkpoint_dir / "dqn_final.pt")


def main() -> None:
    parser = argparse.ArgumentParser(description="Train SuperBot reinforcement learning policies")
    parser.add_argument("--episodes", type=int, default=TrainingConfig.episodes)
    parser.add_argument("--steps", type=int, default=TrainingConfig.steps_per_episode)
    parser.add_argument("--imitation", type=Path, default=None)
    parser.add_argument("--checkpoint", type=Path, default=TrainingConfig.checkpoint_dir)
    args = parser.parse_args()

    config = TrainingConfig(
        episodes=args.episodes,
        steps_per_episode=args.steps,
        imitation_replays=args.imitation,
        checkpoint_dir=args.checkpoint,
    )
    train(config)


if __name__ == "__main__":
    main()
